CREATE TABLE IF NOT EXISTS  `Mytable` (
 id int(40) NOT NULL auto_increment,
 gendar VARCHAR(50) NOT NULL,
 category VARCHAR(100) NOT NULL,
 qualification VARCHAR(50) NOT NULL,
 PRIMARY KEY (id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;