CREATE TABLE IF NOT EXISTS  `myform` (
 id int(40) NOT NULL auto_increment,
 name VARCHAR(150) NOT NULL,
 address VARCHAR(500) NOT NULL,
 gendar VARCHAR(50) NOT NULL,
 gendar1 VARCHAR(50) NOT NULL,
 PRIMARY KEY (id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;