CREATE TABLE IF NOT EXISTS  `Mytable` (
 id int(40) NOT NULL auto_increment,
 name VARCHAR(150) NOT NULL,
 email VARCHAR(150) NOT NULL,
 PRIMARY KEY (id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;