CREATE TABLE IF NOT EXISTS  `testTable` (
 id int(40) NOT NULL auto_increment,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(250) NOT NULL,
 PRIMARY KEY (id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;