CREATE TABLE IF NOT EXISTS  `NewModuleTable` (
 id int(40) NOT NULL auto_increment,
 name VARCHAR(150) NOT NULL,
 address VARCHAR(500) NOT NULL,
 PRIMARY KEY (id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;