CREATE TABLE IF NOT EXISTS  `testTable1` (
 id int(40) NOT NULL auto_increment,
 name VARCHAR(150) NOT NULL,
 email VARCHAR(250) NOT NULL,
 address VARCHAR(500) NOT NULL,
 gendar VARCHAR(50) NOT NULL,
 City VARCHAR() NOT NULL,
 PRIMARY KEY (id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;